version: '3.8'
services:
  comsumer:
    build: .
    image: collect-server:latest
    container_name: collect-server
    networks:
      - omegi-net
    ports:
      - "8051:8051"

networks:
  omegi-net:
    external: true
